x-krill-build: &x-krill-build
  build:
    context: ./krill
    dockerfile: ../Dockerfile
    args:
      - RUN_USER_UID=${RUN_USER_UID}
      - RUN_USER_GID=${RUN_USER_GID}

x-krill-common: &x-krill-common
  command: ["krill", "-c", "/var/krill/krill.conf"]
  image: krill
  #ports:
  #  - 30000:${KRILL_PORT:-3000}

x-krill-env: &x-krill-env
  KRILL_ADMIN_TOKEN: ${KRILL_ADMIN_TOKEN}
  KRILL_LOG_LEVEL: debug
  TZ: Asia/Tokyo
  RUN_USER_UID: ${RUN_USER_UID}
  RUN_USER_GID: ${RUN_USER_GID}

networks:
  krill_net:
    name: krill_net

services:
  # testbed: root RPKI CA
  krill-root:
    <<: [*x-krill-build, *x-krill-common]
    environment:
      <<: [*x-krill-env]
    volumes:
      - ./SHARE:/SHARE:rw
      - ./data-root:/var/krill/data:rw
      - ./conf/krill-root.conf:/var/krill/krill.conf:ro
    networks:
      krill_net:
        aliases:
          - root
          - root.${DOMAIN}

  krill-host1:
    <<: [*x-krill-common]
    environment:
      <<: [*x-krill-env]
    volumes:
      - ./SHARE:/SHARE:rw
      - ./data-host1:/var/krill/data:rw
      - ./conf/krill-host1.conf:/var/krill/krill.conf:ro
    networks:
      krill_net:
        aliases:
          - host1
          - host1.${DOMAIN}

  krill-host2:
    <<: [*x-krill-common]
    environment:
      <<: [*x-krill-env]
    volumes:
      - ./SHARE:/SHARE:rw
      - ./data-host2:/var/krill/data:rw
      - ./conf/krill-host2.conf:/var/krill/krill.conf:ro
    networks:
      krill_net:
        aliases:
          - host2
          - host2.${DOMAIN}

  squid:
    image: ubuntu/squid
    init: true
    ports:
      - "${SQUID_ADDR_PORT:-127.0.0.1:33128}:3128"
    volumes:
      - ./squid-ssl-ports.conf:/etc/squid/conf.d/allow-ssl-ports.conf:ro
    networks:
      krill_net:
