x-krill-build: &x-krill-build
  build:
    context: ./krill
    dockerfile: ../Dockerfile
    args:
      - RUN_USER_UID=${RUN_USER_UID}
      - RUN_USER_GID=${RUN_USER_GID}

x-krill-common: &x-krill-common
  image: krill
  #ports:
  #  - 30000:3000

x-krill-env: &x-krill-env
  KRILL_ADMIN_TOKEN: abcde
  KRILL_LOG_LEVEL: debug
  TZ: Asia/Tokyo
  RUN_USER_UID: ${RUN_USER_UID}
  RUN_USER_GID: ${RUN_USER_GID}

networks:
  krill_net:
    name: krill_net

services:
  # testbed: root RPKI CA
  krill-root:
    command: ["krill", "-c", "/var/krill/krill.conf"]
    <<: [*x-krill-build, *x-krill-common]
    environment:
      <<: [*x-krill-env]
    volumes:
      - ./SHARE:/SHARE:rw
      - ./data-root:/var/krill/data:rw
      - ./conf/krill-root.conf:/var/krill/krill.conf:ro
    networks:
      krill_net:
        aliases:
          - root.krill
          - root.krill.example.org

  krill-host1:
    <<: [*x-krill-common]
    environment:
      - KRILL_ADMIN_TOKEN=abcde
    networks:
      krill_net:
        aliases:
          - host1.krill
          - host1.krill.example.org

  krill-host2:
    <<: [*x-krill-common]
    environment:
      - KRILL_ADMIN_TOKEN=abcde
    networks:
      krill_net:
        aliases:
          - host2.krill
          - host2.krill.example.org

  squid:
    image: ubuntu/squid
    init: true
    ports:
      - "127.0.0.1:33128:3128"
    volumes:
      - ./squid-ssl-ports.conf:/etc/squid/conf.d/allow-ssl-ports.conf:ro
    networks:
      krill_net:
